name: mongo-sharding

services:
  configsvr:
    image: mongo:6.0
    container_name: configsvr
    command: [ "mongod", "--configsvr", "--replSet", "configReplSet", "--bind_ip_all" ]
    ports:
      - "27019:27019"
    volumes:
      - config_data:/data/db

  shard1:
    image: mongo:6.0
    container_name: shard1
    command: [ "mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--bind_ip_all", "--port", "27018" ]
    ports:
      - "27018:27018"
    volumes:
      - shard1_data:/data/db

  shard2:
    image: mongo:6.0
    container_name: shard2
    command: [ "mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--bind_ip_all", "--port", "27016" ]
    ports:
      - "27016:27016"
    volumes:
      - shard2_data:/data/db

  mongos:
    image: mongo:6.0
    container_name: mongos
    depends_on:
      - configsvr
      - shard1
      - shard2
    command: >
      bash -c "sleep 10 && 
      mongos --configdb configReplSet/configsvr:27019 --bind_ip_all --port 27020"
    ports:
      - "27020:27020"

  fast_api:
    container_name: fast_api
    build: 
      context: api_app
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos:27020"
      MONGODB_DATABASE_NAME: "somedb"


volumes:
  config_data:
  shard1_data:
  shard2_data: